version: '3.8'

services:
  # Service 1: Database Server (PostgreSQL)
  postgres:
    image: postgres:15
    container_name: otsuka_db_warehouse
    environment:
      POSTGRES_USER: user_otsuka
      POSTGRES_PASSWORD: password_rahasia_123
      POSTGRES_DB: otsuka_analytics
    ports:
      - "5432:5432" # Mapping port server ke laptop
    volumes:
      - postgres_data:/var/lib/postgresql/data # Agar data tidak hilang saat container mati
    restart: always

# Persistent Volume Storage
volumes:
  postgres_data: